#ifndef S21_MATRIX
#define S21_MATRIX

// #include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define S21_NULL ((void *)0)

#define OK 0
#define INVALID_MATRIX 1
#define CALC_ERROR 2

typedef struct matrix_struct {
  double **matrix;
  int rows;
  int columns;
} matrix_t;

// ❌ 🟡 ✅

// core funcs
int s21_create_matrix(int rows, int columns, matrix_t *result);     // ✅
void s21_remove_matrix(matrix_t *A);                                // ✅
int s21_eq_matrix(matrix_t *A, matrix_t *B);                        // ✅
int s21_sum_matrix(matrix_t *A, matrix_t *B, matrix_t *result);     // ✅
int s21_sub_matrix(matrix_t *A, matrix_t *B, matrix_t *result);     // ✅
int s21_mult_number(matrix_t *A, double number, matrix_t *result);  // ✅
int s21_mult_matrix(matrix_t *A, matrix_t *B, matrix_t *result);    // ✅
int s21_transpose(matrix_t *A, matrix_t *result);                   // ✅
int s21_determinant(matrix_t *A, double *result);                   // ❌
int s21_calc_complements(matrix_t *A, matrix_t *result);            // ❌
int s21_inverse_matrix(matrix_t *A, matrix_t *result);              // ❌

// additional support funcs
int s21_fill_matrix(matrix_t *A, double num, matrix_t *result);            // ✅
int s21_print_matrix(matrix_t *A);                                         // ✅
int s21_input_matrix(matrix_t *A, matrix_t *result);                       // ✅
int s21_is_valid_matrix(matrix_t *A);                                      // ✅
int s21_minor_matrix(matrix_t *A, int row, int column, matrix_t *result);  // ✅

#endif
